export const menuEmpty = [
  {
    image: "/property/flat2.webp",
    _id: "d0330",
    name: "2 bedroom flat",
    category: "property",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/property/flat.webp",
    _id: "d0330",
    name: "bungalow bedroom flat",
    category: "property",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/property/land.webp",
    _id: "d0330",
    name: "3 plots of land",
    category: "property",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/property/house2.webp",
    _id: "d0330",
    name: "2 bedroom flat",
    category: "property",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/property/land2.webp",
    _id: "d0330",
    name: "2 bedroom flat",
    category: "property",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/cream.webp",
    _id: "d030",
    name: "cream blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/herbal.webp",
    _id: "d031",
    name: "herbal mix",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/shoe.webp",
    _id: "d029",
    name: "high quality shoe",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/electronics/phone.jpg",
    _id: "d011d",
    name: "samsung galaxy s9 plus 64 GB blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/electronics/camera.webp",
    _id: "d011",
    name: "surveilance camera hd focus",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/electronics/printer.webp",
    _id: "d013",
    name: "printer hp s9 plus 64 GB blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/electronics/laptop.jpg",
    _id: "d015",
    name: "laptop hp s9 plus 64 GB blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/electronics/fan.jpg",
    _id: "d017",
    name: "fan galaxy s9 plus 64 GB blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/electronics/hset.jpg",
    _id: "d0r16",
    name: "headphones by zealot",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/electronics/hset.jpg",
    _id: "d0d16",
    name: "headphones by zealot",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/electronics/fan.jpg",
    _id: "d017",
    name: "standing fan",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/electronics/remote.webp",
    _id: "d014",
    name: "tv remote blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/electronics/laptop2.webp",
    _id: "d012",
    name: "hp elitebook plus 64 GB blue",
    category: "electronics",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/add6.png",
    _id: "d02",
    name: "O.C.N seat cover ",
    category: "vehicles",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 30000,
  },
  {
    image: "/add5.png",
    _id: "d03",
    name: "self con at hilltop",
    vendor: "lensatic compass",
    category: "property",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 250000,
  },

  {
    image: "/fashion/dress.webp",
    _id: "d020",
    name: "black dress",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/glasses.webp",
    _id: "d021",
    name: "glasses galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/handbag.webp",
    _id: "d022",
    name: "handbag gold",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/necklace.webp",
    _id: "d023",
    name: "necklace galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/palms.webp",
    _id: "d024",
    name: "palms galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/shirt.webp",
    _id: "d025",
    name: "shirt blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/shoe.webp",
    _id: "d026",
    name: "shoe galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/watch.webp",
    _id: "d027",
    name: "watch galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/shoe2.webp",
    _id: "d028",
    name: "shoe galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/shoe.webp",
    _id: "d029",
    name: "shoe galaxy s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/glasses.webp",
    _id: "d0291",
    name: "cartier glasses s9 plus 64 GB blue",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/fashion/dress.webp",
    _id: "d0292",
    name: "black dress",
    category: "fashion",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/health/cream.webp",
    _id: "d030",
    name: "lotion blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/herbal.webp",
    _id: "d031",
    name: "herbal mix",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/perfume.webp",
    _id: "d032",
    name: "perfume blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/pill2.webp",
    _id: "d034",
    name: "conjestion pills blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/serum.webp",
    _id: "d035",
    name: "hyanuloric acid serum",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/polls.webp",
    _id: "d029234",
    name: "shirt blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/slimtea.webp",
    _id: "d0392",
    name: "fat cut",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/cream.webp",
    _id: "d031s",
    name: "herbal mix",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/perfume.webp",
    _id: "d032d",
    name: "perfume blue",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/health/serum.webp",
    _id: "d034w",
    name: "vitaminc c serum",
    category: "health and beauty",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },

  {
    image: "/services/cleaners.jpg",
    _id: "d041",
    name: "professional cleaners",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/repair.webp",
    _id: "d054",
    name: "ac repair technician",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/dispatch.webp",
    _id: "d042",
    name: "dispatch rider",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/floor.webp",
    _id: "d044",
    name: "wallpaper wrapper",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/mechanic.jpg",
    _id: "d0544",
    name: "mechanic",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 18000,
  },
  {
    image: "/services/maid.webp",
    _id: "d044",
    name: "cleaners",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/mechanic.jpg",
    _id: "d0544",
    name: "mechanic",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/milky.webp",
    _id: "d0544",
    name: "milky",
    category: "food",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/pos.webp",
    _id: "d054",
    name: "pos agent",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/usher.webp",
    _id: "d054",
    name: "event ushers",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
  {
    image: "/services/repair.webp",
    _id: "d054",
    name: "ac technician",
    category: "services",
    vendor: "lensatic compass",
    phone: "070789765456",
    desc: "A rich blend of selected malt whiskies giving it an extra smooth and full body test for customers like you. Premium extra whisky. Original Blend.",
    price: 180000,
  },
];

export const storesEmpty = [
  {
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBdprmUeTNQ2Ch0bJ1yuFqm1N1k-naNXgTsKMM8nnB4g&s",
    _id: "01",
    id: "store1",
    name: "chiboy tablets and devices",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Skin_care_cosmetics.jpg/800px-Skin_care_cosmetics.jpg",
    _id: "d02",
    id: "store2",
    name: "ushe's skincare",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "/add3.png",
    _id: "d03",
    id: "store3",
    name: "joechem ventures",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBdprmUeTNQ2Ch0bJ1yuFqm1N1k-naNXgTsKMM8nnB4g&s",
    _id: "d05",
    id: "store4",
    name: "chiboy's electrical services",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
];

export const services = [
  {
    url: "/add6.png",
    _id: "01",
    id: "item1",
    name: "sell ",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "/add5.png",
    _id: "d02",
    id: "item1",
    name: "ushe's cement",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "/add3.png",
    _id: "d03",
    id: "store3",
    name: "joechem ventures",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
  {
    url: "/add6.png",
    _id: "d05",
    id: "store4",
    name: "chiboy's electrical services",
    desc: "deals on powerbanks, smart watches, earpods and more",
  },
];

export const categories = [
  {
    name: " ",
  },
  {
    name: "electronics ",
  },
  {
    name: "services",
  },
  {
    name: "food",
  },
  {
    name: "fashion",
  },
  {
    name: "health and beauty",
  },
  {
    name: "property",
  },
  {
    name: "sports",
  },
  {
    name: "others",
  },
];
